### ISSUE TITLE
`AbiContractForm`

### ISSUE THREAD

**Issue by leovigna** [owlprotocol/web3-redux#126]
## Description
A collection of read/write `AbiItemForm`(s) to interact with a smart contract's interface.

## Components
- `AbiInput`: An input field with validation for different input types (address, uint256, bytes...).
- `AbiForm`: From for a function call on smart contract.
- `AbiContractForm`: Collection of forms for each available function on the interface.

## Features
- Validation for inputs
- Create temp transaction while awaiting for input
- Notify when transactions sent, confirmations
- Read/Write transactions => Calls simply use `web3`, Transactions require connected wallet `web3Sender`

## Tasks
- [] Initial Form design using Reactstrap form
- [] AbiInput validation
- [] AbiForm created by combining inputs
- [] AbiForm connect to web3-redux for backend call / send tx
- [] AbiContractForm generated from abi of stored contract

**Comment by leovigna** [comment]
https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#writeProxyContract

**Comment by leovigna** [comment]
https://docs.soliditylang.org/en/latest/abi-spec.html

**Comment by leovigna** [comment]
https://docs.soliditylang.org/en/latest/abi-spec.html#json

**Comment by leovigna** [comment]
https://web3js.readthedocs.io/en/v1.7.3/web3-utils.html#ishexstrict
https://web3js.readthedocs.io/en/v1.7.3/web3-utils.html#isaddress
https://web3js.readthedocs.io/en/v1.7.3/web3-utils.html#tochecksumaddress

**Comment by leovigna** [comment]
Validate bytes length for fixed byte types.

**Comment by leovigna** [comment]
Use the web3-eth ABI Typescript types.

**Comment by leovigna** [comment]
```
import { AbiItem } from 'web3-utils';
```

**Comment by leovigna** [comment]
```
import { AbiItem } from '../../utils/web3-utils/index.js';
```
